console.log("Receita de sanduíche")
console.log("=> Ingredientes")
console.log("* 2 Fatias de queijo prato")
console.log("* 2 Fatias de presunto")
console.log("* Alface")
console.log("* Tomate")
console.log("* 2 fatias de pão de forma")
console.log("* Maionese")
console.log("=> Modo de preparo")
console.log("* Pegue as duas fatias de pães de forma e passe a maionese em ambas")
console.log("* Coloque as fatias de queijo e de presunto")
console.log("* Coloque o alface e o tomate na quantidade que você preferir")
console.log("=> Bom apetite")    